### ISSUE TITLE
feat : web 배포

### ISSUE THREAD

**Issue by 11t518s** [Amattang/Amattang-Frontend#18]
## 설명
서버 api 나온 후 해당 navigation만 연결
웹배포 이후 url 연결

## todos
 - [ ] 웹 베포 이후 공유하기 버튼 테스트
 - [x] 웹 배포
 - [ ] set navigation routing
 - [ ] netlify CI/CD
