### ISSUE TITLE
feat: 내항목

### ISSUE THREAD

**Issue by 11t518s** [Amattang/Amattang-Frontend#35]
## 설명
체크리스트 내부 내 항목 설정

## Todos
 - [ ] 아무런 내 항목이 없으면 기본 화면이 나온다.
 - [ ] 내 항목이 1개 이상일 경우 그 항목이 메인타이틀과 함께 나온다.
 - [ ] ADD된 항목을 클릭하면 하단에 항목 추가로 추가된 항목들이 보인다.
 - [ ] ADD된 항목 하단에 추가된 항목은 왼쪽에 체크박스를 통해 체크할 수 있다.
 - [ ] ADD된 체크리스트 오른쪽에 ...을 누르면해당 그룹을 편집할 수 있다.

 - [ ] 새 그룹 Add누르면 바텀시트가 올라온다.
 - [ ] 바텀시트 오른쪽 위에는 삭제 버튼이 있다.
 - [ ] 버텀시트 메인 타이틀을 수정할 수 있다. (default : 새 그룹)
 - [ ] 항목추가 를 누르면 키보드를 기반으로 문자를 입력할 수 있다.
 - [ ] 입력된 문자열을 누르면 마찬가지로 수정할 수 있다.
 - [ ] 입력하고 나면 오른쪽에 체크박스가 생기고 체크할 수 있다.
 - [ ] 입력하고 나면 아래쪽에 새로운 항목 추가 칸이 생긴다.
