### ISSUE TITLE
fix: QA

### ISSUE THREAD

**Issue by 11t518s** [Amattang/Amattang-Frontend#38]
## 설명
텍스트 입력 시 화면이 같이 위로 올라가게하기
기본 체크리스트 삭제 및 추가하기 로직 재 설정
삭제 스크롤과 위아래 스크롤 마찰을 줄이기

## todos
 - [x] 텍스트 인풋시 같이 화면 올리기
 - [x] 삭제 및 추가하기 로직 재 설정
 - [x] 스크롤 불편함 개선
